var Blockly4Arduino = Blockly4Arduino || {};
Blockly4Arduino.LOCALISED_TEXT = {
  translationLanguage: "Nederlands",
  title: "Ingegno Blockly4Arduino",
  blocks: "Blokken",
  /* Menu */
  open: "Open",
  save: "Opslaan",
  deleteAll: "Verwijder Alles",
  settings: "Voorkeuren",
  documentation: "Documentatie",
  reportBug: "Fout melden",
  examples: "Voorbeelden",
  /* Settings */
  compilerLocation: "",
  compilerLocationDefault: "",
  sketchFolder: "",
  sketchFolderDefault: "",
  arduinoBoard: "Arduino Bord",
  arduinoBoardDefault: "Arduino Bord Ongekend",
  comPort: "",
  comPortDefault: "",
  defaultIdeButton: "",
  defaultIdeButtonDefault: "",
  language: "Taal",
  languageDefault: "Taal onbekend",
  sketchName:  "Schets Naam",
  /* Arduino console output */
  arduinoOpMainTitle:  "",
  arduinoOpWaiting:  "",
  arduinoOpUploadedTitle:  "",
  arduinoOpVerifiedTitle:  "",
  arduinoOpOpenedTitle:  "",
  arduinoOpOpenedBody:  "",
  arduinoOpErrorUpVerTitle:  "",
  arduinoOpErrorSketchTitle:  "",
  arduinoOpErrorFlagTitle:  "",
  arduinoOpErrorFlagPrefTitle:  "",
  arduinoOpErrorIdeDirTitle:  "",
  arduinoOpErrorIdeDirBody:  "",
  arduinoOpErrorIdeOptionTitle:  "",
  arduinoOpErrorIdeOptionBody:  "",
  arduinoOpErrorIdePortTitle:  "",
  arduinoOpErrorIdePortBody:  "",
  arduinoOpErrorIdeBoardTitle:  "",
  arduinoOpErrorIdeBoardBody:  "",
  /* Modals */
  noServerTitle: "",
  noServerTitleBody:  "",
  addBlocksTitle: "Extra Blokken",
  /* Alerts */
  loadNewBlocksTitle: "Laad nieuwe blokken?",
  loadNewBlocksBody: "Een nieuw XML bestand laden zal alle huidige blokken op je werkruimte vervangen.\n\n" +
                     "Ben je zeker dat je wil doorgaan?",
  discardBlocksTitle: "Verwijder blokken?",
  discardBlocksBody: "Er zijn %1 blokken op de werkruimte.<br>" +
                     "Ben je zeker dat je ze wil verwijderen?",
  invalidXmlTitle: "Ongeldige XML",
  invalidXmlBody: "Het XML bestand kon niet gesplitst worden in blokken. Controleer de XML code en probeer opnieuw.",
  /* Tooltips */
  uploadingSketch: "",
  uploadSketch: "",
  verifyingSketch: "",
  verifySketch: "",
  openingSketch: "",
  openSketch: "",
  notImplemented: "Functie nog niet geimplementeerd.",
  /* Prompts */
  ok: "OK",
  okay: "Okay",
  cancel: "Annuleer",
  return: "Keer terug",
  /* Cards */
  arduinoSourceCode: "Arduino Code",
  blocksXml: "XML Blokken",
  /* Toolbox Categories*/
  catLogic: "Logica",
  catLoops: "Herhalen",
  catMath: "Wiskunde",
  catText: "Tekst",
  catVariables: "Variabelen",
  catFunctions: "Functies",
  catInputOutput: "In/Output",
  catTime: "Tijd",
  catAudio: "Audio",
  catMotors: "Motoren",
  catComms: "Comms",
};
